changelog:
  exclude:
    labels:
      - ignore-for-release
      - release
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - enhancement
        - semver-minor
    - title: Fixes
      labels:
        - bug
        - semver-patch
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - dependencies
        - ci
        - chore
    - title: Other changes
      labels:
        - "*"
